# Generated by Django 5.2.14 on 2026-07-23 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_user_profile_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sertifikat / Natija nomi')),
                ('file', models.FileField(upload_to='certificates/', verbose_name='PDF yoki Rasm fayli')),
                ('score', models.CharField(blank=True, max_length=50, null=True, verbose_name='Imtihon bali / Natijasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Sertifikat va Natija',
                'verbose_name_plural': 'Sertifikatlar va Natijalar',
            },
        ),
    ]
