# Generated by Django 5.2.14 on 2026-07-23 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kurs nomi')),
                ('description', models.TextField(verbose_name='Kurs tavsifi')),
                ('icon_class', models.CharField(default='fa-laptop-code', max_length=50, verbose_name='Ikonka klassi')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='F.I.O')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('called', "Bog'lanildi"), ('enrolled', "O'qishni boshladi"), ('canceled', 'Rad etildi')], default='new', max_length=10, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='students.course', verbose_name='Qiziqqan kursi')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Test nomi')),
                ('file', models.FileField(upload_to='tests/', verbose_name='Savollar PDF yoki Rasm fayli')),
                ('answers_key', models.TextField(blank=True, null=True, verbose_name='Javoblar kaliti (MCQ uchun, masalan: A,B,C,D)')),
                ('test_type', models.CharField(choices=[('MCQ', 'Test (A,B,C,D)'), ('WRITTEN', 'Yozma ish')], default='MCQ', max_length=10, verbose_name='Test turi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tests', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='students.group', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
            },
        ),
        migrations.CreateModel(
            name='StudentTestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answers', models.TextField(blank=True, null=True, verbose_name="O'quvchi javoblari")),
                ('uploaded_solution', models.FileField(blank=True, null=True, upload_to='solutions/', verbose_name='Yozma ish rasmi/PDF')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Baho (Ball %)')),
                ('status', models.CharField(choices=[('started', 'Boshladi'), ('completed', 'Topshirdi'), ('disqualified', 'Chetlashtirildi')], default='started', max_length=15, verbose_name='Holati')),
                ('cheated_at', models.DateTimeField(blank=True, null=True, verbose_name='Qoidabuzarlik vaqti')),
                ('submitted_at', models.DateTimeField(auto_now=True, verbose_name='Topshirilgan vaqti')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_submissions', to='students.student', verbose_name="O'quvchi")),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Topshirilgan Test',
                'verbose_name_plural': 'Topshirilgan Testlar',
                'unique_together': {('student', 'test')},
            },
        ),
    ]
