# Generated by Django 5.2.14 on 2026-07-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dars beradigan fani'),
        ),
    ]
