# Generated by Django 5.2.14 on 2026-07-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_profile_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='admin_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Admin Telefon Raqami'),
        ),
    ]
