# Generated by Django 5.2.14 on 2026-07-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_lead_admin_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_manage_staff',
            field=models.BooleanField(default=False, verbose_name="Ustoz va Admin Qo'shish huquqi"),
        ),
    ]
