# Generated by Django 5.2.14 on 2026-07-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_profile_can_manage_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='raw_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Ko'rinadigan parol"),
        ),
    ]
