# Generated by Django 5.2.14 on 2026-07-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_profile_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='answers_file',
            field=models.FileField(blank=True, null=True, upload_to='test_keys/', verbose_name='Javoblar kaliti fayli (TXT yoki Rasm/PDF)'),
        ),
    ]
