# Generated by Django 5.2.14 on 2026-07-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_test_answers_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_type',
        ),
        migrations.AlterField(
            model_name='test',
            name='answers_file',
            field=models.FileField(blank=True, null=True, upload_to='test_answers/', verbose_name='Javoblar fayli (TXT/PDF/Rasm)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='answers_key',
            field=models.TextField(blank=True, null=True, verbose_name='Javoblar kaliti (masalan: A,B,C,D)'),
        ),
    ]
