# Generated by Django 5.2.14 on 2026-07-28 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_test_test_type_alter_test_answers_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_teacher_cert',
            field=models.BooleanField(default=False, verbose_name='Ustoz Sertifikati'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Ustoz'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(default="350 000 so'm/oy", max_length=50, verbose_name='Kurs narxi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil rasmi'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ota-onasining telefoni'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.student', verbose_name="O'quvchi"),
        ),
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateField(verbose_name='Kuni'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.PositiveSmallIntegerField(verbose_name='Baho (0-10)'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('DAILY', 'Kuntartib dars bahosi'), ('EXAM', 'Imtihon bahosi')], default='DAILY', max_length=10, verbose_name='Baho turi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi akkaunti'),
        ),
    ]
