# Generated by Django 5.2.14 on 2026-07-29 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_certificate_is_teacher_cert_certificate_teacher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_phone',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='is_teacher_cert',
            field=models.BooleanField(default=False, verbose_name='Ustoz sertifikati'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(default="300 000 so'm/oy", max_length=100, verbose_name='Kurs oylik narxi'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(verbose_name='Baho'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('HW', 'Uy vazifasi'), ('ACT', 'Darsdagi faollik'), ('EXAM', 'Imtihon')], max_length=4, verbose_name='Baho turi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Akkaunti'),
        ),
    ]
