# Generated by Django 5.2.14 on 2026-07-29 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_remove_certificate_teacher_remove_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='extra_groups',
            field=models.ManyToManyField(blank=True, related_name='extra_students', to='students.group', verbose_name="Qo'shimcha Guruhlari"),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.group', verbose_name='Asosiy Guruhi'),
        ),
    ]
