# Generated by Django 5.2.14 on 2026-07-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_student_extra_groups_alter_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='subject',
            field=models.CharField(default='Matematika', max_length=100, verbose_name="Fan yoki Yo'nalish"),
        ),
    ]
