# Generated by Django 5.2.14 on 2026-07-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_certificate_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='mcq_count',
            field=models.IntegerField(default=30, verbose_name='Variantli (A,B,C,D) savollar soni'),
        ),
        migrations.AddField(
            model_name='test',
            name='written_count',
            field=models.IntegerField(default=0, verbose_name='Ochiq / Yozma savollar soni'),
        ),
        migrations.AlterField(
            model_name='test',
            name='answers_key',
            field=models.TextField(blank=True, null=True, verbose_name='Javoblar kaliti (masalan: A,B,C,D yoki 36:158, 37:8)'),
        ),
    ]
