# Generated by Django 5.2.14 on 2026-07-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_test_mcq_count_test_written_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duration_minutes',
            field=models.IntegerField(default=60, verbose_name='Imtihon vaqti (daqiqa)'),
        ),
    ]
