# Generated by Django 5.2.14 on 2026-07-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_test_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh/Sababi'),
        ),
    ]
