# Generated by Django 5.2.14 on 2026-08-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_attendance_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tests/', verbose_name='Savollar PDF yoki Rasm fayli'),
        ),
    ]
